networks:
  main:
    # driver: bridge

services:
  apache-php:
    build: ./apache-php
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www/html
    networks:
      - main
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    env_file:
      - ./mysql/.env
    entrypoint: sh -c "/usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/entrypoint:/docker-entrypoint-initdb.d
    networks:
      - main

  phpmyadmin:
    image: phpmyadmin
    env_file:
      - ./phpmyadmin/.env
    ports:
      - "3307:80"
    networks:
      - main
    depends_on:
      - mysql

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      API_URL: http://localhost/api/app/openapi
    ports:
      - "8080:8080"
